//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeInCity.StringResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BikeInCity.StringResources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AppBar_About {
            get {
                return ResourceManager.GetString("AppBar_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string AppBar_All {
            get {
                return ResourceManager.GetString("AppBar_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change city.
        /// </summary>
        public static string AppBar_ChangeCity {
            get {
                return ResourceManager.GetString("AppBar_ChangeCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to directions.
        /// </summary>
        public static string AppBar_Directions {
            get {
                return ResourceManager.GetString("AppBar_Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string AppBar_Here {
            get {
                return ResourceManager.GetString("AppBar_Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy policy.
        /// </summary>
        public static string AppBar_PrivacyPolicy {
            get {
                return ResourceManager.GetString("AppBar_PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search.
        /// </summary>
        public static string AppBar_Search {
            get {
                return ResourceManager.GetString("AppBar_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn off gps.
        /// </summary>
        public static string AppBar_TurnOffGPS {
            get {
                return ResourceManager.GetString("AppBar_TurnOffGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to turn on gps.
        /// </summary>
        public static string AppBar_TurnOnGPS {
            get {
                return ResourceManager.GetString("AppBar_TurnOnGPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.bikeincity.com.
        /// </summary>
        public static string AppInformation {
            get {
                return ResourceManager.GetString("AppInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of GPS data
        ///
        ///Bike In City uses the GPS device of your phone to obtain your current location. This location is later used to obtain the nearest bike stations. This data specifying your current location is not send over the network to a secondary storage or treatment and is not stored on any other place than in the memory of your phone.
        ///
        ///You can disable the use of GPS device of your phone in the application menu by selecting “turn off gps” as well as by disabling the GPS in your phone settings..
        /// </summary>
        public static string AppPrivacyPolicy {
            get {
                return ResourceManager.GetString("AppPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@bikeincity.com.
        /// </summary>
        public static string AppSupport {
            get {
                return ResourceManager.GetString("AppSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bike In City.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.0.0.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address not found.
        /// </summary>
        public static string Message_AddressNotFound {
            get {
                return ResourceManager.GetString("Message_AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has been an error while connecting to internet. Please check you network connection..
        /// </summary>
        public static string Message_ConnectionError {
            get {
                return ResourceManager.GetString("Message_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GPS is initializing..
        /// </summary>
        public static string Message_GPS_Init {
            get {
                return ResourceManager.GetString("Message_GPS_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GPS does not receive any data..
        /// </summary>
        public static string Message_GPS_NoData {
            get {
                return ResourceManager.GetString("Message_GPS_NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GPS is currently off..
        /// </summary>
        public static string Message_GPS_OFF {
            get {
                return ResourceManager.GetString("Message_GPS_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cities..
        /// </summary>
        public static string Message_LoadingCities {
            get {
                return ResourceManager.GetString("Message_LoadingCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading stations..
        /// </summary>
        public static string Message_LoadingStations {
            get {
                return ResourceManager.GetString("Message_LoadingStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application did not receive expected information. Please check you network connection..
        /// </summary>
        public static string Message_NotSupported {
            get {
                return ResourceManager.GetString("Message_NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The station list was not loaded..
        /// </summary>
        public static string Message_StationsNotLoaded {
            get {
                return ResourceManager.GetString("Message_StationsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified error occured during the execution of the application..
        /// </summary>
        public static string Message_UnspecifiedError {
            get {
                return ResourceManager.GetString("Message_UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TextBoxAbout {
            get {
                return ResourceManager.GetString("TextBoxAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information:.
        /// </summary>
        public static string TextBoxInformation {
            get {
                return ResourceManager.GetString("TextBoxInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near:.
        /// </summary>
        public static string TextBoxNearTo {
            get {
                return ResourceManager.GetString("TextBoxNearTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string TextBoxPrivacyPolicy {
            get {
                return ResourceManager.GetString("TextBoxPrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes:.
        /// </summary>
        public static string TextBoxRoutes {
            get {
                return ResourceManager.GetString("TextBoxRoutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support:.
        /// </summary>
        public static string TextBoxSupport {
            get {
                return ResourceManager.GetString("TextBoxSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title:.
        /// </summary>
        public static string TextBoxTitle {
            get {
                return ResourceManager.GetString("TextBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string TextBoxTo {
            get {
                return ResourceManager.GetString("TextBoxTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version:.
        /// </summary>
        public static string TextBoxVersion {
            get {
                return ResourceManager.GetString("TextBoxVersion", resourceCulture);
            }
        }
    }
}
